[tool.poetry]
name = "wagtail-modeltranslation"
version = "0.11rc3"
license = "New BSD"
authors = ["InfoPortugal S.A."]
readme = 'README.rst'
description = "Translates Wagtail CMS models using a registration approach."
repository = "https://github.com/infoportugal/wagtail-modeltranslation"
keywords = ["django", "wagtail", "translation", "i18n"]
include = [
    "*.txt",
    "*.rst",
    "docs",
    "*.rst",
    "conf.py",
    "wagtail_modeltranslation/static/**",
    "wagtail_modeltranslation/management/**",
    "wagtail_modeltranslation/templatetags/**",
    "wagtail_modeltranslation/templates/**",
    ]
exclude = ["*.pyc", "*.DS_Store"]

[tool.poetry.dependencies]
python = "^3.6"
django = ">=3.0"
wagtail = ">=2.13,<3.0"

[tool.poetry.dev-dependencies]
bumpversion = "*"
wheel = "*"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"